### ISSUE TITLE
Tell us in the README about the cool implemented libraries

### ISSUE THREAD

**Issue by xandark** [dschmenk/PLASMA#11]
I still can't get over how incredible this programming environment is! I wish I had it 30 years ago...

I keep checking in on this project from time to time and what would really help me, and I think others as well, is to have a listing of the included libraries somewhere in the documentation. 

For example, I notice there is a very cool double lo-res library which is exactly what I've been looking for, but if I didn't randomly poke around into the source tree on my own initiative, I would've assumed that it wasn't present and my estimation of Plasma would've been unfairly diminished. That it has these cool abilities should be declared loudly to everyone.

I think that this kind of addedum should appear high up in the README, because I want to know what kinds of cool things are already implemented for me. Like, does it have hi-res abilities? Or DHGR? Or sound? Or wave-table playback? I noticed that this has cooperative multi-tasking! That is so cool! Please tell us right away that it exists and which file to look in! :)

On that note, I wish that the source files had more documentation for how to use the functions. I feel like I can figure it out, but it'd be easier if a comment just told me explicitly 1) what the module does and 2) what the inputs to the function are expected to be with any side effects noted.

**Comment by dschmenk** [comment]
Yeah, the documentation is a real problem. And most of the libraries are serious WIP. There hasn't been a great deal of QA on any of them. I've checked them in just so I don't forget what I did. Now, if anyone would like to help ;-)

**Comment by dschmenk** [comment]
Documenting the libraries and sample code in the Wiki...
