### ISSUE TITLE
dgr.pla broken and won't build

### ISSUE THREAD

**Issue by dschmenk** [dschmenk/PLASMA#12]
Assembly code not inside function definition. Fix-ups for assembly routines now out of sync with locations in code.

**Comment by peterferrie** [comment]
fixed in 655fa8df4a0931831245166cf8a287c4808f1e6c

**Comment by dschmenk** [comment]
Not fixed. Reverted to working version.

**Comment by peterferrie** [comment]
> Not fixed. Reverted to working version.

This one is building.  What's the problem?

**Comment by dschmenk** [comment]
It was crashing to the monitor when running DGRTEST. Just because it builds doesn't mean it works.
