### ISSUE TITLE
Typo in doc?

### ISSUE THREAD

**Issue by lifepillar** [dschmenk/PLASMA#14]
I followed the steps to build the “Hello, world” example. It works for me if I use the following commands:

```
plasm -AM < hello.pla >hello.a
acme --setpc 4094 -o 'HELLO#FE1000' hello.a
plvm HELLO
```
which is what `make hello` does, in fact. The documentation, however, has:

```
acme --setpc 4094 -o HELLO hello.a
```

Is that a typo?

**Comment by dschmenk** [comment]
Yep. Thanks!
