### ISSUE TITLE
Use #0 to specify no return codes on cmdsys functions?

### ISSUE THREAD

**Issue by ZornsLemma** [dschmenk/PLASMA#20]
I was looking at the bytecode output the other day to see if I could spot any optimisation opportunities and I noticed that CALL xxx:DROP is very common.

A lot - not all - of these were calls to cmdsys functions. Before you reach v1.0, could these maybe be declared to return no arguments using the new #0 syntax?

As well/instead, a new 'CALLDROP' opcode might be a net code size win, but it feels a little inelegant - I thought I'd mention it though.

**Comment by dschmenk** [comment]
That's absolutely what I intend to do. I'm just not emotionally ready to edit and test all those functions yet ;-)

**Comment by ZornsLemma** [comment]
Thanks Dave, I hope my e-mail didn't cause too much emotional strain by raising the thought of it. :-)

When you do this I'm happy to do some testing on it, if (for example) you want to do it on a branch so I can see it before you merge it to master. Just let me know...

**Comment by dschmenk** [comment]
Thanks Steve. I'm finishing up lambda (anonymous) functions before eating the rest of my vegetables. Once that is done, 1.o should pretty much be ready to, barring any new requests.

**Comment by dschmenk** [comment]
Should be all implemented now.
