### ISSUE TITLE
Bug in dhcp.pla and/or compiler bug?

### ISSUE THREAD

**Issue by ZornsLemma** [dschmenk/PLASMA#27]
Hi Dave,

I noticed this while playing around with some tweaks to the optimiser and reviewing its effect on the generated bytecode; dhcp.pla may be fine, but I thought I'd mention it.

dhcp.pla has this line:
```
 if pkt=>dhcp_xid:0 == $0201 and pkt=>dhcp_xid:2 = $0403
```
Shouldn't that second condition use '==' not '='?

The generated code also looks a bit odd, incidentally. If this is valid PLASMA code I might expect it (C-like) to assign $0403 to pkt=>dhcp_xid:2 and behave like 'and TRUE' because $0403 is non-0. The generated code doesn't seem to do that, though:
```
; <stdin>: 0189:     if pkt=>dhcp_xid:0 == $0201 and pkt=>dhcp_xid:2 = $0403
        !BYTE   $58,$12,$05             ; ENTER 18,5
; <stdin>: 0190:         when pkt->dhcp_opts.[parseopts(@pkt->dhcp_opts, 53) + 2]
; <stdin>: 0191:            is DHCP_OFFER
        !BYTE   $66,$04                 ; LLW   [4]
        !BYTE   $2A,$04                 ; CB    4
        !BYTE   $02                     ; ADD
        !BYTE   $62                     ; LW
        !BYTE   $2C,$01,$02             ; CW    513
        !BYTE   $40                     ; ISEQ
        !BYTE   $66,$04                 ; LLW   [4]
        !BYTE   $2A,$04                 ; CB    4
        !BYTE   $02                     ; ADD
        !BYTE   $2A,$02                 ; CB    2
        !BYTE   $02                     ; ADD
        !BYTE   $62                     ; LW
        !BYTE   $24                     ; LAND
        !BYTE   $4C                     ; BRFLS _B017
        !WORD   _B017-*
        !BYTE   $2C,$03,$04             ; CW    1027
        !BYTE   $30                     ; DROP
```
If I read that correctly, it is as if the source code were:
```
 if pkt=>dhcp_xid:0 == $0201 and pkt=>dhcp_xid:2
```
i.e. the $0403 seems to be ignored. Could this be a compiler bug? I'd expect it to either assign then test-against-0, or for this to generate a compile error.

Cheers.

Steve

**Comment by dschmenk** [comment]
Yes and yes. Just when I thought I was wrapping it up...

**Comment by dschmenk** [comment]
Not a pretty fix - I will clean up shortly. But it did find the syntax bug in dhcp.pla and a few others as well. Must say that some music sequencing code I wrote really shone with the optimizer. Your work is greatly appreciated!
