### ISSUE TITLE
Possible bug in lambda function LEAVE

### ISSUE THREAD

**Issue by ZornsLemma** [dschmenk/PLASMA#31]
I haven't tried to trigger this bug yet, but just looking at codegen.c's emit_lambdafunc(), it seems to emit an incorrect LEAVE opcode with no argument:
```
    if (cparams)
        printf("\t%s\t$5A\t\t\t; LEAVE\n", DB);
```
Apologies if this isn't a real bug, but I thought I should mention it before I forget...

Cheers.

Steve

**Comment by dschmenk** [comment]
Thanks Steve! Great catch. I actually got it right in the self-hosted compiler, but missed it in the cross compiler. Odd that the portable VM did'nt catch it. I'll have to update its checks.

**Comment by dschmenk** [comment]
Steve-
I should mention that there has been a lot of discussion on VM improvements here:

https://groups.google.com/forum/?fromgroups#!topic/comp.sys.apple2.programmer/aFY8pKRSaIQ

Definitely worth reviewing.

Dave...
