### ISSUE TITLE
make test fails on OS X

### ISSUE THREAD

**Issue by marvinmalkowskijr** [dschmenk/PLASMA#45]
When attempting to execute the unit tests(make test) to ensure PLASMA is working correctly, it fails with the following errors.

bash-3.2$ make test
./plasm -AMOW  < samplesrc/test.pla > samplesrc/test.a

<stdin>  126:   a             = vals123
                                       ^
Warning: Silently dropping extra rvalues

<stdin>  142:   return 0
                        ^
Warning: Too few return values
acme --setpc 4094 -o TEST#FE1000 samplesrc/test.a
./plasm -AMOW  < samplesrc/testlib.pla > samplesrc/testlib.a
acme --setpc 4094 -o TESTLIB#FE1000 samplesrc/testlib.a
./plvm TEST
Load module TEST

Error: symbols TESTLIB not found in symbol table.
Load module TESTLIB
testlib loaded!
1 10 100 1000 10000
1 10 100 1000 10000
1000
900
800
700
600
500
400
300
200
100
0
-100
-200
-300
-400
-500
-600
-700
-800
-900
-1000
Eval stack over/underflow! - $033D: $76 [-1]
$033F: $30 [ ]
warning: this program uses gets(), which is unsafe.

**Comment by dschmenk** [comment]
The Portable VM has been updated to be in-sync with the real VMs. Should be all better now.

Thanks Marvin!

Dave...
