### ISSUE TITLE
80 columns support on apple iie

### ISSUE THREAD

**Issue by tsupplis** [dschmenk/PLASMA#48]
I see the code does not support 80 columns on apple ii, is it worth trying to add it or have you got it in plan?
I am happy to give it a go. Any recommendation?

**Comment by dschmenk** [comment]
None of the code explicitly uses 80 column text mode, but it doesn't preclude it either. All that is required is to set the sys flags to use the AUX text page 1 and set the COUT/CIN vectors.

Having said that, there are a few issues when deciding what kind of 80 column support you want. Simple stuff, like in conio, is pretty easy although not very fast using the above approach. If you want fast, then you need to write directly to screen memory. You have to consider 80 column support on the Apple ][ and ][+ which can use a myriad of 80 column hardware, at least to the point of future implementation on those machines.

This is why I haven't committed to a library targeting 80 column support yet. I eventually want to get to a character UI style library that is fast and works on a range of hardware from the Videx 80 column cards to the IIe/IIc 80 column hardware. If you want to take a stab at it, by all means go for it. Having a starting point for further development is better than not.
