### ISSUE TITLE
DINTRP opt?

### ISSUE THREAD

**Issue by JohnMBrooks** [dschmenk/PLASMA#55]
Could this:

DINTRP  PLA
        CLC
        ADC     #$01
        STA     IPL
        PLA
        ADC     #$00
        STA     IPH
        LDY     #$00
        JMP     FETCHOP

be replaced with:

DINTRP  PLA
        STA     IPL
        PLA
        STA     IPH
        LDY     #$01
        JMP     FETCHOP

**Comment by dschmenk** [comment]
Hi John-

Huh, look at that. Looks good to me! Thanks for spending time looking at this, I haven't done anything with this in months. Time to blow the dust off.

Thank,
Dave...

**Comment by JohnMBrooks** [comment]
I was just watching this:
https://youtu.be/zdJnz6-d060

then then browsing the source in Github, then comparing to PLASMA...

**Comment by dschmenk** [comment]
I've been following along at 6502.org: http://forum.6502.org/viewtopic.php?f=1&t=2236

I haven't watched the video yet, so thanks for the link. A more traditional register based CPU-like VM. Easy write direct code with, but will probably require a somewhat more intelligent compiler than the brain-dead PLASMA compiler.

**Comment by dschmenk** [comment]
Just as a reminder to myself: Y register needs to be zero at any of the xxINTRP entry points. The ENTER opcode depends on this for it's own optimization. Since DINTRP is seldom called compared to IINTRP, it's best to leave DINTRP as-is.
