### ISSUE TITLE
License less for non-statics linked work

### ISSUE THREAD

**Issue by kwccoin** [dschmenk/PLASMA#57]
Not sure but it seems even if I write a simple game on this require gpl 3.  A bit too restrictive.  The core is like an os. Wonder.

**Comment by dschmenk** [comment]
Good point. Originally the GPL3 was used to keep the VM definition from straying. There was only the VM and the compiler. Now, with all the libraries (and more on the way), it makes sense to alter the library module licenses. I have no problem moving to the LGPL3 for modules. I'll ask if anyone else does.

**Comment by dschmenk** [comment]
Switched to LGPL3. Should make it easier to write apps against the PLASMA modules.
