### ISSUE TITLE
Uthernet cards and emulation

### ISSUE THREAD

**Issue by audetto** [dschmenk/PLASMA#63]
Hi,

I found this blog http://schmenk.is-a-geek.com/wordpress/?p=258 and wanted to check how well the Uthernet II emulation in AppleWin works with this code.

I have not been able to get it to work, but I don't think it is even trying to use it.
I tried to execute `+tftpd` with the Uthernet II card in any slot and it has never been accessed.

I tried as well Uthernet (1) in slot 3 but the result has been almost the same

![image](https://user-images.githubusercontent.com/212523/173191645-ad6a90b3-34a3-4683-ac43-76434d78d824.png)

With a minimal change that the card is access in an "invalid" way: `WARNING! Reading write-only TFE register $04!`

Is there anything I need to do to configure either Uthernet 1 or 2?

**Comment by dschmenk** [comment]
With the latest version of AppleWin and the Uthernet II emulation, PLASMA identifies the card in slot #3
